document.write('<footer class="footr_area">'
+ '<div class="footer_widget_area">'
+    '<div class="container">'
+        '<div class="row footer_widget_inner">'
+            '<div class="col-lg-4 col-sm-6">'
+                '<aside class="f_widget f_about_widget">'
+                    '<img src="img/footerlogo.png" alt="">'
+                    '<br>'
+                    '<ul class="unorderlist">'
+                        '<li><a target="_blank" href="disclaimer.html">Disclaimer</a></li>'
+                        '<li><a target="_blank" href="privacy.html">Privacy Statement</a></li>'
+                       '<li><a target="_blank" href="contact.html">Contact Us</a></li>'
+                   '</ul>' 
+               '</aside>'
+               '</div>'
+               '<div class="col-lg-4 col-sm-6">'
+                '<aside class="f_widget f_insta_widget">'
+               '<div class="f_title">'
+                  '<h3>Facebook</h3>'
+                '</div>'
+                     '<ul>'
+        '<li><a href="https://www.facebook.com/Hamdardfoundationpakistan/photos/a.872722632785005.1073741849.792730200784249/872722689451666/?type=3&theater" target="_blank"><img src="img/fb/contract.jpg" alt=""></a></li>'
+        '<li><a href="https://www.facebook.com/Hamdardfoundationpakistan/photos/a.869250819798853.1073741846.792730200784249/1593189867404941/?type=3&theater" target="_blank"><img src="img/fb/naunehalassembly.jpg" alt=""></a></li>'
+        '<li><a href="https://www.facebook.com/Hamdardfoundationpakistan/photos/a.802133999843869.1073741838.792730200784249/1592960917427836/?type=3&theater" target="_blank"><img src="img/fb/shura.jpg" alt=""></a></li>'
+        '<li><a href="https://www.facebook.com/Hamdardfoundationpakistan/photos/a.802138783176724.1073741840.792730200784249/802138993176703/?type=3&theater" target="_blank"><img src="img/fb/mobile_despeansary.jpg" alt=""></a></li>'
+        '<li><a href="https://www.facebook.com/Hamdardfoundationpakistan/photos/a.1593209357402992.1073741856.792730200784249/1593211417402786/?type=3&theater" target="_blank"><img src="img/fb/hakim_matab.jpg" alt=""></a></li>'
+        '<li><a href="https://www.facebook.com/Hamdardfoundationpakistan/" target="_blank"><img src="img/fb/hamdard_public_schoo_H33df.jpg" alt=""></a></li>'
+        '<li><a href="https://www.facebook.com/Hamdardfoundationpakistan/" target="_blank"><img src="img/fb/services.jpg" alt=""></a></li>'
+        '<li><a href="https://www.facebook.com/Hamdardfoundationpakistan/" target="_blank"><img src="img/fb/history.jpg" alt=""></a></li>'
+                 '</ul>'
+               '</aside>'
+            '</div>'
+             '<div class="col-lg-4 col-sm-6">'
+             '<aside class="f_widget f_subs_widget">'
+             '<div class="f_title">'
+             '<h3>Subscribe to newsletter</h3>'
+    '</div>'
+    '<div class="input-group">'
+        '<input type="text" class="form-control" placeholder="Your e-mail address here" aria-label="Your e-mail address here">'
+        '<span class="input-group-btn">'
+           ' <button class="more_btn btn-secondary submit_btn" type="button">Subscribe</button>'
+       '</span>'
+    '</div>'
+ '</aside>'
+               '</div>'
+            '</div>'
+           '</div>'   
+           '</div>' 
+              '<div class="footer_copyright">'
+               '<div class="container">'
+    '<div class="float-sm-left">'
+        '<h5>'
+'Copyright &copy;'
+'<script>document.write(new Date().getFullYear());</script> '
+'All rights reserved <!--| This website is developed<i class="fa fa-heart-o" aria-hidden="true"></i>  by  <a href="https://www.facebook.com/CircleHouseSoftwareCompany/" target="_blank">CircleHouse --></a>'
+'</h5>'
+   ' </div>'
+    '<div class="float-sm-right">'
+        '<ul>'
+           ' <li><a href="https://www.facebook.com/Hamdardfoundationpakistan/" target="_blank"><i class="fa fa-facebook"></i></a></li>'
+           ' <li><a href="https://twitter.com/search?q=hamdard&src=typd" target="_blank"><i class="fa fa-twitter"></i></a></li>'
+           ' <li><a href="https://www.linkedin.com/company/hamdard/" target="_blank"><i class="fa fa-linkedin"></i></a></li>'
+        '</ul>'
+    '</div>'
+'</div>'
+'</div>'
+ '</footer>')