document.write('<header class="main_menu_area">'
 +'<div id="cssmenu">'
 + '<ul>'
 +' <li><a href="index.html">Home</a></li>'
 +  ' <!-- Who we are -->'
 +   '<li class="active"><a href="whoweare.html">Who we are</a>'
 +   '<ul>'
 +    '<li><a href="missionstatement.html">Mission Statement</a></li>'
 +    '<li><a href="history.html">History</a></li>'
 +    '<li><a href="journeyhfp.html">Journey of Hamdard Foundation Pakistan</a></li>'
 +  '</ul>'
 +  '</li>'
 +    ' <!-- Leadership -->'
 +     '<li class="active"><a href="leadership.html">Leadership</a>'
 +     '<ul>'
 +      '<li><a href="founder.html">Founder</a></li>'
 +      '<li><a href="president.html">president</a></li>'
 +      '<li><a href="vicepresident.html">Vice President</a></li>'
 +      '<li><a href="directorgeneral.html">Director General</a></li>'
 +      '<li><a href="Majlis-e-Nozama.html">Majlis-e-Nozama</a></li>'
 +    '</ul>'
 +   '</li>'
 +    '  <!-- Health -->'
 +      '<li class="active"><a href="health.html">Health</a>'
 +    '<ul>'
 +      '<li><a href="hamdardmatab.html">Hamdard Matab</a></li>'
 +     ' <li><a href="tajmedical.html">Hamdard University Hospital (Taj Medical Complex)</a>'
 +       ' <ul>'
 +          ' <li><a href="freetaj.html">Free Patient Scheme Hamdard University Hospital (Taj Medical Complex)</a></li>'
 +       '</ul>'
 +    '</li>'
 +     '<li><a href="dental.html">Hamdard University Dental Hospital North Nazimabad</a></li>'
 +     '<li><a href="shifahospital.html">Shifa-ul-Mulk Memorial Hospital</a></li>'
 +     '<li><a href="childcare.html">Niamat Begum Mother and Child Care Centre</a></li>'
 +     '<li><a href="mobiledispensary.html">Hamdard Free Mobile Dispensary</a></li>'
 +   '</ul>'
 +  '</li>'
 +     ' <!-- Education -->'
 +     '<li class="active"><a href="education.html">Education</a>'
 +      '<ul>'
 +    '<li><a href="madinat.html">Madinat al Hikmah</a>'
 +       '<ul>'
 +          '<li><a href="institutes.html">Hamdard Institutes</a></li>'
 +       '</ul>'
 +    '</li>'
 +    '<li><a href="bait.html">Bait al Hikmah</a>'
 +       '<ul>'
 +          '<li><a href="stock.html">Stock</a></li>'
 +          '<li><a href="specificsubject.html">Specific Subject</a></li>'
 +          '<li><a href="specialcollection.html">Special Collection</a></li>'
 +         '<li><a href="standardeducation.html">Standard of Education</a></li>'
 +          '<li><a href="fumigationsection.html">Fumigation Section</a></li>'
 +          '<li><a href="paperclippings.html">News Paper Clippings</a></li>'
 +          '<li><a href="librarycommitee.html">Library Commitee</a></li>'
 +       '</ul>'
 +    '</li>'
 +    '<li><a href="herbalscience.html">Dr Hafiz Mohammad Ilyas Institute of Pharmacology & Herbel Sciences</a></li>'
 +    '<li><a href="publicschool.html">Hamdard Public School</a></li>'
 +    '<li><a href="pechscampus.html">Hamdard Public School P.E.C.H.S Campus</a></li>'
 +    '<li><a href="villageschool.html">Hamdard Village School</a></li>'
 +  '</ul>'
 + '</li>'
 +  ' <!-- Scholarship -->'
 +    '<li class="active"><a href="scholarship.html">SCHOLARSHIP</a>'
 +     '<ul>'
 +    '<li><a href="hsscholarship.html">Hakim Mohammed Said Scholarship</a></li>'
 +    '<li><a href="educationalaid.html">Educational Aid</a></li>'
 +    '</ul>'
 +    '</li>'
 +     '<!-- Philanthropy -->'
 +    '<li class="active"><a href="Philanthropy.html">PHILANTHROPY</a>'
 +    '<ul>'
 +      '<li><a href="institutionalaid.html">Institutional Aid</a></li>'
 +      '<li><a href="financialaid.html">Financial Aid</a></li>'
 +      '<li><a href="ramzanration.html">Ramzan Ration</a></li>'
 +      '<li><a href="blanket.html">Distribution of Blanket/Quilts</a></li>'
 +      '<li><a href="heatwave.html">Campaign against the Heat Wave</a></li>'
 +   '</ul>'
 +   '</li>'
 +   '<!-- Publication -->'
 +    '<li class="active"><a href="publication.html">PUBLICATION</a>'
 +  '<ul>'
 +    '<li><a href="hamdardnaunheal.html">Hamdard Naunehal</a></li>'
 +     '<li><a href="hamdardsehat.html">Hamdard Sehat</a></li>'
 +    '<li><a href="hamdardislamicus.html">Hamdard Islamicus</a></li>'
 +    '<li><a href="hamdardmedicus.html">Hamdard Medicus</a></li>'
 +    '<li><a href="hamdardhistory.html">Hamdard Historicus</a></li>'
 +    '<li><a href="hamdardchild.html">List of Hamdard Publications for Children</a></li>'
 +    '<li><a href="urdupublication.html">List of Urdu Publications</a></li>'
 +    '<li><a href="englishpublication.html">List of English Publications</a></li>'
 +  '</ul>'
 +  '</li>'
 +   '<!-- Conference -->'
 +    '<li class="active"><a href="conference.html">CONFERENCE</a>'
 +  '<ul>'
 +    '<li><a href="hamdardassembly.html">Hamdard Naunehal Assembly</a></li>'
 +    '<li><a href="shurahamdard.html">Shura Hamdard</a></li>'
 +    '<li><a href="childhealthconf.html">International Children’s Health Conference</a></li>'
 +    '<li><a href="eaternmidicine.html">Promotion of Tradition of Eastern Medicine in Pakistan</a></li>'
 +    '<li><a href="grantcontract.html">Grant Contract</a></li>'
 +  '</ul>'
 +  '</li>'
 + '<li class="active"><a href="contact.html">Contact Us</a></li>'
 + '</ul>'
 + '</div>'
 + '</header>')