document.write(  '<div id="breaking-news-container">'
 +               ' <div id="breaking-news-colour" class="slideup animated">'
 +                ' </div>'
 +                '  <span style="color: red;" class="breaking-news-title delay-animated slidein">'
+                '     ** News **'
+              '     </span> '
+                '   <a style="color: white" class="breaking-news-headline delay-animated2 fadein marquee">'
+                 'Hamdard Islamicus for the month of June and July is now available.'
+                 '</a> ' 
+               '</div> <br>'
)