document.write('<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">'
+      '<ol class="carousel-indicators">'
+           '<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>'
+           '<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>'
+           '<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>'
+           '<li data-target="#carouselExampleIndicators" data-slide-to="3"></li>'
+           '<li data-target="#carouselExampleIndicators" data-slide-to="4"></li>'
+     '</ol>'
+      '<div class ="nav">'
+       '<div class="carousel-inner">'
+        '<div class="carousel-item active">'
+         '<img class="d-block w-100" src="img/s1.PNG" alt="First slide">'
+            '<div class="carousel-caption d-none d-md-block">'
+             '<div class="content">'  
+             '<h5 class="navbartext">Founder</h5>'
+             '<p class="navbarp">A Country that wishes to be great and respected needs true and strong men</p>'
+             '</div>'
+        '</div>'
+    '</div>'
+    '<div class="carousel-item">'
+      '<img class="d-block w-100" src="img/s2.PNG" alt="Second slide">'
+        '<div class="carousel-caption d-none d-md-block">'
+            '<h5 class="navbartext">Shura Hamdard</h5>'
+            '<p class="navbarp">Sham-i-Hamdard, dialogue with a galaxy of prominent scientists, historians, culturists, educationists, writers, poets.</p>'
+      '</div>'
+     '</div>'
+      '<div class="carousel-item">'
+       '<img class="d-block w-100" src="img/s3.PNG" alt="Third slide">'
+       '<div class="carousel-caption d-none d-md-block">'
+            '<h5 class="navbartext">History</h5>'
+            '<p class="navbarp">Hakeem Hafiz Abdul Majeed established Hamdard Dawakhana at Delhi, India in 1906..</p>'
+      '</div>'
+     '</div>'
+       '<div class="carousel-item">'
+       '<img class="d-block w-100" src="img/s4.PNG" alt="Third slide">'
+       '<div class="carousel-caption d-none d-md-block">'
+            '<h5 class="navbartext">Naunehal Assembly</h5>'
+            '<p class="navbarp">Bazm-i-Hamdard Naunehal i.e. Hamdard Children forum now Naunehal Assembly. From 1985 to 1994.</p>'
+      '</div>'
+      '</div>'
+       '<div class="carousel-item">'
+         '<img class="d-block w-100" src="img/s5.PNG" alt="Third slide">'
+          '<div class="carousel-caption d-none d-md-block">'
+            '<h5 class="navbartext">Grant Contract</h5>'
+            '<p class="navbarp">On February 10, 2015, Mr. Akira Ouchi, the Consul General of Japan in Karachi and Mrs. Sadia Rashid, '
+            'the President of Hamdard Foundation signed the Grant Contract at the Japan Information and Culture Center of the Consulate General of Japan.</p>'
+          '</div>'
+     '</div>'
+   '</div>'
+ '</div>'
+     ' <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">'
+         '<span class="carousel-control-prev-icon" aria-hidden="true"></span>'
+         '<span class="sr-only">Previous</span>'
+      '</a>'
+ '<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">'
+  '<span class="carousel-control-next-icon" aria-hidden="true"></span>'
+  '<span class="sr-only">Next</span>'
+ '</a>'
+ '</div>')